version: '3'
services:
  db:
    image: mysql:5.7.36
    platform: linux/amd64
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysql_test_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: secret
        TZ: 'Asia/Tokyo'
    ports:
        - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/infra/local/mysql:/var/lib/mysql

  php:
    build: ./.docker/php
    volumes:
      - ./src/laravel:/var/www

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src/laravel:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:14.18-alpine
    container_name: "node14.18-alpine"
    # コンテナ内の標準出力とホストの出力を設定：trueを指定
    tty: true
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./src/laravel:/var/www
    # コンテナ起動後のカレントディレクトリを設定
    working_dir: /var/www
